name: Android CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    # Create APK Debug
    - name: Build apk debug project (APK)
      run: ./gradlew assembleDebug
    # Create an artifacts folder if it doesn't exist, and move APK into it
    - name: Move APK to artifacts folder
      run: |
        mkdir -p ${{ github.workspace }}/artifacts/
        mv ${{ env.main_project_module }}/build/outputs/apk/debug/* ${{ github.workspace }}/artifacts/
    - name: Upload APK Debug - ${{ env.repository_name }}
      uses: actions/upload-artifact@v3
      with:
        name: Tasky_debug
        path: ${{ github.workspace }}/artifacts/
